language: go

before_script:
 - git clone git://github.com/minhtule/PredictionIO-Mock-Server.git
 - cd PredictionIO-Mock-Server
 - npm install
 - node app.js &
 - sleep 3  # Give mock server some time to bind to sockets, etc
 - cd ..

go:
 - 1.1
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - release
 - tip

script:
 - go test -v ./...
